export const verbosCurs = [  ["Trabajar", "Work"],
  ["Mirar", "Look"],
  ["Escuchar", "Listen"],
  ["Repetir", "Repeat"],
  ["Levantarse", "Get up"],
  ["Almorzar", "Have lunch"],
  ["Jugar", "Play"],
  ["Cenar", "Have dinner"],
  ["Dormir", "Sleep"],
  ["Cocinar", "Cook"],
  ["Leer", "Read"],
  ["Practicar", "Practice"],
  ["Gustar", "Like"],
  ["Amor", "Love"],
  ["Hacer-Domésticas", "Do household chores"],
  ["Estudiar", "Study"],
  ["Cepillarse los dientes", "Brush your teeth"],
  ["Tener", "Have"],
  ["Sentarse", "Sit"],
  ["Ir", "Go"],
  ["Ser", "Be"],
  ["Estar", "Be"],
  ["Hacer", "Do"],
  ["Decir", "Say"],
  ["Ver", "See"],
  ["Poder", "Can"],
  ["Querer", "Want"],
  ["Pensar", "Think"],
  ["Creer", "Believe"],
  ["Llevar", "Wear"],
  ["Comprar", "Buy"],
  ["Vender", "Sell"],
  ["Llegar", "Arrive"],
  ["Salir", "Go out"],
  ["Entrar", "Enter"],
  ["Regresar", "Return"],
  ["Viajar", "Travel"],
  ["Conducir", "Drive"],
  ["Correr", "Run"],
  ["Caminar", "Walk"],
  ["Tomar", "Take"],
  ["Buscar", "Look for"],
  ["Encontrar", "Find"],
  ["Esperar", "Wait"],
  ["Ayudar", "Help"],
  ["Hacer ejercicio", "Exercise"],
  ["Escuchar música", "Listen to music"],
  ["Ver televisión", "Watch TV"],
  ["Navegar por internet", "Surf the internet"]
];

export const coloresCurs = [
  ['Blanco', 'White'],
  ['Negro', 'Black'],
  ['Gris', 'Gray'],
  ['Rojo', 'Red'],
  ['Azul', 'Blue'],
  ['Verde', 'Green'],
  ['Amarillo', 'Yellow'],
  ['Naranja', 'Orange'],
  ['Marrón', 'Brown'],
  ['Morado', 'Purple'],
  ['Rosa', 'Pink'],
  ['Turquesa', 'Turquoise'],
  ['Ocre', 'Ochre'],
  ['Beige', 'Beige'],
  ['Café', 'Coffee'],
  ['Celeste', 'Sky blue'],
  ['Dorado', 'Gold'],
  ['Plateado', 'Silver'],
  ['Esmeralda', 'Emerald'],
  ['Índigo', 'Indigo'],
  ['Lila', 'Lilac'],
  ['Marfil', 'Ivory'],
  ['Mostaza', 'Mustard'],
  ['Púrpura', 'Purple'],
];
export const pronombresCurs = [  
  ["Yo", "I"],
  ["Tú", "You"],
  ["Él", "He"],
  ["Ella", "She"],
  ["Ello", "It"],
  ["Nosotros", "We"],
  ["Ustedes", "You"],
  ["Ellos/Ellas", "They"]
];
export const numerosCurs = [  
  ["1", "One"],
  ["2", "Two"],
  ["3", "Three"],
  ["4", "Four"],
  ["5", "Five"],
  ["6", "Six"],
  ["7", "Seven"],
  ["8", "Eight"],
  ["9", "Nine"],
  ["10", "Ten"],
  ["11", "Eleven"],
  ["12", "Twelve"],
  ["13", "Thirteen"],
  ["14", "Fourteen"],
  ["15", "Fifteen"],
  ["16", "Sixteen"],
  ["17", "Seventeen"],
  ["18", "Eighteen"],
  ["19", "Nineteen"],
  ["20", "Twenty"],
  ["30", "Thirty"],
  ["40", "Forty"],
  ["50", "Fifty"],
  ["60", "Sixty"],
  ["70", "Seventy"],
  ["80", "Eighty"],
  ["90", "Ninety"],
  ["100", "One hundred"],
  ["200", "Two hundred"],
  ["300", "Three hundred"],
  ["400", "Four hundred"],
  ["500", "Five hundred"],
  ["600", "Six hundred"],
  ["700", "Seven hundred"],
  ["800", "Eight hundred"],
  ["900", "Nine hundred"],
  ["1000", "One thousand"]
];

export const mesesCurs = [  
  ["Enero", "January"],
  ["Febrero", "February"],
  ["Marzo", "March"],
  ["Abril", "April"],
  ["Mayo", "May"],
  ["Junio", "June"],
  ["Julio", "July"],
  ["Agosto", "August"],
  ["Septiembre", "September"],
  ["Octubre", "October"],
  ["Noviembre", "November"],
  ["Diciembre", "December"]
];
export const diasSemanaCurs = [  
  ["Lunes", "Monday"],
  ["Martes", "Tuesday"],
  ["Miércoles", "Wednesday"],
  ["Jueves", "Thursday"],
  ["Viernes", "Friday"],
  ["Sábado", "Saturday"],
  ["Domingo", "Sunday"]
];

export const saludosCurs = [  ["Hola", "Hello"],
  ["Buenos días", "Good morning"],
  ["Buenas tardes", "Good afternoon"],
  ["Buenas noches", "Good evening"],
  ["¿Qué tal?", "How are you?"],
  ["¿Cómo estás?", "How are you?"],
  ["¿Cómo te va?", "How's it going?"],
  ["¿Qué hay de nuevo?", "What's new?"],
  ["¿Qué has estado haciendo?", "What have you been up to?"],
  ["¿Cómo ha sido tu día?", "How has your day been?"],
  ["Bienvenido", "Welcome"],
  ["Encantado de conocerte", "Nice to meet you"],
  ["Adiós", "Goodbye"],
  ["Hasta luego", "See you later"],
  ["Hasta pronto", "See you soon"],
  ["Nos vemos", "See you"],
  ["Chao", "Bye"],
  ["Que tengas un buen día", "Have a nice day"],
  ["Que descanses", "Rest well"],
  ["Buen provecho", "Enjoy your meal"],
  ["Felicidades", "Congratulations"],
  ["Feliz cumpleaños", "Happy birthday"],
  ["Feliz Navidad", "Merry Christmas"],
  ["Feliz año nuevo", "Happy new year"],
  ["Gracias", "Thank you"],
  ["De nada", "You're welcome"],
  ["Por favor", "Please"],
  ["Lo siento", "I'm sorry"],
  ["Perdón", "Excuse me"],
  ["Con permiso", "Excuse me"],
  ["Salud", "Bless you"],
  ["¿Cómo lo haces?", "How do you do it?"],
  ["Me alegro de verte", "Good to see you"],
  ["Me alegra saber de ti", "Glad to hear from you"],
  ["¿En qué puedo ayudarte?", "How can I help you?"],
  ["Mejórate pronto", "Get well soon"],
  ["¡Qué envidia!", "I'm so jealous!"]
];

const familiares = [  
  ['Padre', 'Father'],
  ['Madre', 'Mother'],
  ['Hermano', 'Brother'],
  ['Hermana', 'Sister'],
  ['Abuelo', 'Grandfather'],
  ['Abuela', 'Grandmother'],
  ['Tío', 'Uncle'],
  ['Tía', 'Aunt'],
  ['Primo', 'Cousin (male)'],
  ['Prima', 'Cousin (female)'],
  ['Hijo', 'Son'],
  ['Hija', 'Daughter'],
  ['Nieto', 'Grandson'],
  ['Nieta', 'Granddaughter'],
  ['Sobrino', 'Nephew'],
  ['Sobrina', 'Niece'],
  ['Cuñado', 'Brother-in-law'],
  ['Cuñada', 'Sister-in-law'],
  ['Yerno', 'Son-in-law'],
  ['Nuera', 'Daughter-in-law']
];
const objetosCasa = [  
  ['Mesa', 'Table'],
  ['Silla', 'Chair'],
  ['Sofá', 'Sofa'],
  ['Cama', 'Bed'],
  ['Armario', 'Wardrobe'],
  ['Cómoda', 'Chest of drawers'],
  ['Lámpara', 'Lamp'],
  ['Almohada', 'Pillow'],
  ['Cortina', 'Curtain'],
  ['Manta', 'Blanket'],
  ['Televisor', 'Television'],
  ['Refrigerador', 'Refrigerator'],
  ['Horno', 'Oven'],
  ['Microondas', 'Microwave'],
  ['Estufa', 'Stove'],
  ['Fregadero', 'Sink'],
  ['Baño', 'Bathroom'],
  ['Espejo', 'Mirror'],
  ['Toalla', 'Towel'],
  ['Cepillo', 'Brush'],
  ['Secador de pelo', 'Hair dryer'],
  ['Plancha', 'Iron'],
  ['Aspiradora', 'Vacuum cleaner'],
  ['Escoba', 'Broom'],
  ['Basura', 'Garbage'],
  ['Caja', 'Box'],
  ['Jarrón', 'Vase'],
  ['Reloj', 'Clock'],
  ['Libro', 'Book'],
  ['Candado', 'Padlock']
];

const animales = [  
  ['Perro', 'Dog'],
  ['Gato', 'Cat'],
  ['Caballo', 'Horse'],
  ['Vaca', 'Cow'],
  ['Cerdo', 'Pig'],
  ['Oveja', 'Sheep'],
  ['Conejo', 'Rabbit'],
  ['Ratón', 'Mouse'],
  ['Pájaro', 'Bird'],
  ['Pato', 'Duck'],
  ['Gallina', 'Chicken'],
  ['Pavo', 'Turkey'],
  ['Abeja', 'Bee'],
  ['Hormiga', 'Ant'],
  ['León', 'Lion'],
  ['Tigre', 'Tiger'],
  ['Elefante', 'Elephant'],
  ['Jirafa', 'Giraffe'],
  ['Cebra', 'Zebra'],
  ['Hipopótamo', 'Hippopotamus'],
  ['Rinoceronte', 'Rhinoceros'],
  ['Mono', 'Monkey'],
  ['Gorila', 'Gorilla'],
  ['Oso', 'Bear'],
  ['Zorro', 'Fox'],
  ['Lobo', 'Wolf'],
  ['Canguro', 'Kangaroo'],
  ['Koala', 'Koala'],
  ['Pingüino', 'Penguin'],
  ['Ballena', 'Whale']
];
export const titulosProfesionales = [
  ["Abogado/a", "Lawyer"],
  ["Médico/a", "Doctor"],
  ["Ingeniero/a", "Engineer"],
  ["Arquitecto/a", "Architect"],
  ["Diseñador/a", "Designer"],
  ["Programador/a", "Programmer"],
  ["Científico/a", "Scientist"],
  ["Psicólogo/a", "Psychologist"],
  ["Enfermero/a", "Nurse"],
  ["Administrador/a", "Administrator"],
  ["Analista", "Analyst"],
  ["Asesor/a", "Consultant"],
  ["Auditor/a", "Auditor"],
  ["Comunicador/a", "Communicator"],
  ["Contador/a", "Accountant"],
  ["Economista", "Economist"],
  ["Empresario/a", "Entrepreneur"],
  ["Escritor/a", "Writer"],
  ["Investigador/a", "Researcher"],
  ["Periodista", "Journalist"],
  ["Profesor/a", "Teacher"],
  ["Psiquiatra", "Psychiatrist"],
  ["Publicista", "Publicist"],
  ["Secretario/a", "Secretary"],
  ["Sociólogo/a", "Sociologist"],
  ["Traductor/a", "Translator"],
  ["Veterinario/a", "Veterinarian"],
  ["Chef", "Chef"],
  ["Dentista", "Dentist"],
  ["Farmacéutico/a", "Pharmacist"]
];
//HARDAWARE

const hardwareTecno = [
  ["Procesador", "Processor"],
  ["Memoria RAM", "RAM Memory"],
  ["Disco Duro", "Hard Drive"],
  ["Placa Madre", "Motherboard"],
  ["Tarjeta Gráfica", "Graphics Card"],
  ["Tarjeta de Sonido", "Sound Card"],
  ["Fuente de Poder", "Power Supply"],
  ["Disco de Estado Sólido", "Solid State Drive (SSD)"],
  ["Tarjeta de Red", "Network Card"],
  ["Tarjeta de Captura", "Capture Card"],
  ["Unidad Óptica", "Optical Drive"],
  ["Ventilador", "Fan"],
  ["Enfriador", "Cooler"],
  ["Caja/Torre", "Case/Tower"],
  ["Conexión Inalámbrica", "Wireless Connection"],
  ["Conexión por Cable", "Wired Connection"],
  ["Puerto Ethernet", "Ethernet Port"],
  ["Monitor", "Monitor"],
  ["Teclado", "Keyboard"],
  ["Mouse", "Mouse"],
  ["Altavoces", "Speakers"],
  ["Micrófono", "Microphone"],
  ["Webcam", "Webcam"],
  ["Auriculares", "Headphones"],
  ["Impresora", "Printer"],
  ["Escáner", "Scanner"],
  ["Proyector", "Projector"],
  ["Pantalla Táctil", "Touch Screen"],
  ["Sistema Operativo", "Operating System"],
  ["Alfombrilla de ratón", "Mouse pad"],
  ["Memoria caché", "Cache memory"],
  ["Escáner", "Scanner"],
  ["Impresora", "Printer"],
  ["Plotter", "Plotter"],
  ["Proyector", "Projector"]
];

// FRONTEND
const frontendWords = [
  ["Interfaz de usuario", "User interface"],
  ["Experiencia de usuario", "User experience"],
  ["Diseño responsivo", "Responsive design"],
  ["Accesibilidad", "Accessibility"],
  ["Usabilidad", "Usability"],
  ["Diseño visual", "Visual design"],
  ["Tipografía", "Typography"],
  ["Colores", "Colors"],
  ["Paleta de colores", "Color palette"],
  ["Iconos", "Icons"],
  ["Imágenes", "Images"],
  ["Animación", "Animation"],
  ["Transiciones", "Transitions"],
  ["Efectos", "Effects"],
  ["Scroll", "Scroll"],
  ["Scroll infinito", "Infinite scroll"],
  ["Carga dinámica", "Lazy loading"],
  ["Carga progresiva", "Progressive loading"],
  ["Comprimir imágenes", "Image compression"],
  ["Optimizar", "Optimize"],
  ["Metadatos", "Metadata"],
  ["Microdatos", "Microdata"],
  ["Esquema", "Schema"],
  ["Formularios", "Forms"],
  ["Validación", "Validation"],
  ["HTML semántico", "Semantic HTML"],
  ["Estilos", "Styles"],
  ["Selectores", "Selectors"],
  ["Modelo de caja", "Box model"],
  ["Flexbox", "Flexbox"],
  ["Grid", "Grid"],
  ["Responsive web design", "Responsive web design"],
  ["Librerías", "Libraries"],
  ["Manipulación del DOM", "DOM manipulation"],
  ["Eventos", "Events"],
  ["Promesas", "Promises"],
  ["Reactivo", "Reactive"],
  ["Componentes", "Components"],
  ["Enrutamiento", "Routing"],
  ["Estado", "State"],
  ["Gestión del estado", "State management"],
  ["Depuración", "Debugging"]
];

//CSS
const cssWords = [
  ['Selector', 'Selector'],
  ['Propiedad', 'Property'],
  ['Valor', 'Value'],
  ['Estilo', 'Style'],
  ['Hoja de Estilo', 'Stylesheet'],
  ['Fondo', 'Background'],
  ['Borde', 'Border'],
  ['Tipo de Letra', 'Font Family'],
  ['Tamaño de Letra', 'Font Size'],
  ['Negrita', 'Bold'],
  ['Cursiva', 'Italic'],
  ['Subrayado', 'Underline'],
  ['Color', 'Color'],
  ['Margen', 'Margin'],
  ['Padding', 'Padding'],
  ['Ancho', 'Width'],
  ['Alto', 'Height'],
  ['Posición', 'Position'],
  ['Izquierda', 'Left'],
  ['Derecha', 'Right'],
  ['Arriba', 'Top'],
  ['Abajo', 'Bottom'],
  ['Flotar', 'Float'],
  ['Limpiar', 'Clear'],
  ['Pantalla', 'Display'],
  ['Visibilidad', 'Visibility'],
  ['Opacidad', 'Opacity'],
  ['Overflow', 'Overflow'],
  ['Z-Index', 'Z-Index'],
  ['Cursor', 'Cursor'],
  ['Alinear Texto', 'Text Align'],
  ['Decoración de Texto', 'Text Decoration'],
  ['Transformación de Texto', 'Text Transform'],
  ['Espacio Entre Palabras', 'Word Spacing'],
  ['Espacio Entre Líneas', 'Line Height'],
  ['Sombras', 'Box Shadow'],
  ['Transiciones', 'Transitions'],
  ['Animaciones', 'Animations'],
  ['Gradientes', 'Gradients'],
  ['Bordes Redondeados', 'Border Radius'],
  ['Fuentes de Íconos', 'Icon Fonts'],
  ['Flexbox', 'Flexbox'],
  ['Grid', 'Grid'],
  ['Media Queries', 'Media Queries'],
  ['Pseudoclases', 'Pseudo-Classes'],
  ['Pseudoelementos', 'Pseudo-Elements']
];











